### ISSUE TITLE
Request: Telnet/SSH output

### ISSUE THREAD

**Issue by FrozenBeard** [2called-chaos/mcl#17]
The one thing I miss from Remote Toolkit was the ability to display my live server console and interact with it via telnet, this would be fantastic for shared servers that cant use SSH to connect.

**Comment by 2called-chaos** [comment]
Just cleaning up.

Raw telnet access is unsafe af, therefore I will close this and [console access](https://github.com/2called-chaos/mcl#console-access) is theoretically usable without SSH but it requires a local MCL installation and manual copy from the autoconfig file (`tmp/<name>.sockinfo`) well and data transport will be unsafe.

**Comment by FrozenBeard** [comment]
Ticket update from 2014! Holy moly.
For anyone that may find this in a google search, DiscordSRV has a console section, so you can see/control your console from Discord.

I personally ended up getting 2x dedicated servers and have proper SSH access now.
